// -----------------------------------------------------------------------
// <copyright file="CrudGenerationTests.cs" company="Andrii Kurdiumov">
// Copyright (c) Andrii Kurdiumov. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

namespace SqlMarshal.Tests;

using Microsoft.CodeAnalysis;
using Microsoft.VisualStudio.TestTools.UnitTesting;

[TestClass]
public class CrudGenerationTests : CodeGenerationTestBase
{
    [TestMethod]
    public void FindAll_IList_Sync()
    {
        string source = @"
#nullable enable
namespace Foo
{
    class TestEntity
    {
        public int Id { get; set; }

        public string Name { get; set; }
    }
    
    [Repository(typeof(TestEntity))]
    partial class C
    {
        private DbConnection connection;

        public partial IList<TestEntity> FindAll();
    }
}";
        string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

        Assert.IsNotNull(output);

        var expectedOutput = @"// <auto-generated>
// Code generated by Stored Procedures Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
#pragma warning disable 1591

namespace Foo
{
    using System;
    using System.Collections.Generic;
    using System.Data.Common;
    using System.Linq;

    partial class C
    {
        public partial IList<Foo.TestEntity> FindAll()
        {
            var connection = this.connection;
            using var command = connection.CreateCommand();

            var sqlQuery = @""SELECT id, name FROM test_entity"";
            command.CommandText = sqlQuery;
            using var reader = command.ExecuteReader();
            var __result = new List<TestEntity>();
            while (reader.Read())
            {
                var item = new TestEntity();
                var value_0 = reader.GetValue(0);
                item.Id = (int)value_0;
                var value_1 = reader.GetValue(1);
                item.Name = value_1 == DBNull.Value ? (string?)null : (string)value_1;
                __result.Add(item);
            }

            reader.Close();
            return __result;
        }
    }
}";
        Assert.AreEqual(expectedOutput, output);
    }

    [TestMethod]
    public void FindById_IList_Sync()
    {
        string source = @"
#nullable enable
namespace Foo
{
    class TestEntity
    {
        public int Id { get; set; }

        public string Name { get; set; }
    }
    
    [Repository(typeof(TestEntity))]
    partial class C
    {
        private DbConnection connection;

        public partial TestEntity? FindById(int id);
    }
}";
        string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

        Assert.IsNotNull(output);

        var expectedOutput = @"// <auto-generated>
// Code generated by Stored Procedures Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
#pragma warning disable 1591

namespace Foo
{
    using System;
    using System.Collections.Generic;
    using System.Data.Common;
    using System.Linq;

    partial class C
    {
        public partial Foo.TestEntity? FindById(int id)
        {
            var connection = this.connection;
            using var command = connection.CreateCommand();

            var idParameter = command.CreateParameter();
            idParameter.ParameterName = ""@id"";
            idParameter.Value = id;

            var parameters = new DbParameter[]
            {
                idParameter,
            };

            var sqlQuery = @""SELECT id, name FROM test_entity WHERE id = @id"";
            command.CommandText = sqlQuery;
            command.Parameters.AddRange(parameters);
            using var reader = command.ExecuteReader(System.Data.CommandBehavior.SingleResult | System.Data.CommandBehavior.SingleRow);
            if (!reader.Read())
            {
                return null;
            }

            var __result = new TestEntity();
            var value_0 = reader.GetValue(0);
            __result.Id = (int)value_0;
            var value_1 = reader.GetValue(1);
            __result.Name = value_1 == DBNull.Value ? (string?)null : (string)value_1;
            reader.Close();
            return __result;
        }
    }
}";
        Assert.AreEqual(expectedOutput, output);
    }

    [TestMethod]
    public void Count_int_Sync()
    {
        string source = @"
#nullable enable
namespace Foo
{
    class TestEntity
    {
        public int Id { get; set; }

        public string Name { get; set; }
    }
    
    [Repository(typeof(TestEntity))]
    partial class C
    {
        private DbConnection connection;

        public partial int Count();
    }
}";
        string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

        Assert.IsNotNull(output);

        var expectedOutput = @"// <auto-generated>
// Code generated by Stored Procedures Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
#pragma warning disable 1591

namespace Foo
{
    using System;
    using System.Collections.Generic;
    using System.Data.Common;
    using System.Linq;

    partial class C
    {
        public partial int Count()
        {
            var connection = this.connection;
            using var command = connection.CreateCommand();

            var sqlQuery = @""SELECT COUNT(1) FROM test_entity"";
            command.CommandText = sqlQuery;
            var __result = command.ExecuteScalar();
            return (int)__result!;
        }
    }
}";
        Assert.AreEqual(expectedOutput, output);
    }

    [TestMethod]
    public void DeleteAll_IList_Sync()
    {
        string source = @"
#nullable enable
namespace Foo
{
    class TestEntity
    {
        public int Id { get; set; }

        public string Name { get; set; }
    }
    
    [Repository(typeof(TestEntity))]
    partial class C
    {
        private DbConnection connection;

        public partial void DeleteAll();
    }
}";
        string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

        Assert.IsNotNull(output);

        var expectedOutput = @"// <auto-generated>
// Code generated by Stored Procedures Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
#pragma warning disable 1591

namespace Foo
{
    using System;
    using System.Collections.Generic;
    using System.Data.Common;
    using System.Linq;

    partial class C
    {
        public partial void DeleteAll()
        {
            var connection = this.connection;
            using var command = connection.CreateCommand();

            var sqlQuery = @""DELETE FROM test_entity"";
            command.CommandText = sqlQuery;
            command.ExecuteNonQuery();
        }
    }
}";
        Assert.AreEqual(expectedOutput, output);
    }

    [TestMethod]
    public void DeleteById_IList_Sync()
    {
        string source = @"
#nullable enable
namespace Foo
{
    class TestEntity
    {
        public int Id { get; set; }

        public string Name { get; set; }
    }
    
    [Repository(typeof(TestEntity))]
    partial class C
    {
        private DbConnection connection;

        public partial void DeleteById(int id);
    }
}";
        string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

        Assert.IsNotNull(output);

        var expectedOutput = @"// <auto-generated>
// Code generated by Stored Procedures Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
#pragma warning disable 1591

namespace Foo
{
    using System;
    using System.Collections.Generic;
    using System.Data.Common;
    using System.Linq;

    partial class C
    {
        public partial void DeleteById(int id)
        {
            var connection = this.connection;
            using var command = connection.CreateCommand();

            var idParameter = command.CreateParameter();
            idParameter.ParameterName = ""@id"";
            idParameter.Value = id;

            var parameters = new DbParameter[]
            {
                idParameter,
            };

            var sqlQuery = @""DELETE FROM test_entity WHERE id = @id"";
            command.CommandText = sqlQuery;
            command.Parameters.AddRange(parameters);
            command.ExecuteNonQuery();
        }
    }
}";
        Assert.AreEqual(expectedOutput, output);
    }

    [TestMethod]
    public void Update_void_Sync()
    {
        string source = @"
#nullable enable
namespace Foo
{
    class TestEntity
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }
    }
    
    [Repository(typeof(TestEntity))]
    partial class C
    {
        private DbConnection connection;

        public partial void Update(int id, string name, string description);
    }
}";
        string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

        Assert.IsNotNull(output);

        var expectedOutput = @"// <auto-generated>
// Code generated by Stored Procedures Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
#pragma warning disable 1591

namespace Foo
{
    using System;
    using System.Collections.Generic;
    using System.Data.Common;
    using System.Linq;

    partial class C
    {
        public partial void Update(int id, string name, string description)
        {
            var connection = this.connection;
            using var command = connection.CreateCommand();

            var idParameter = command.CreateParameter();
            idParameter.ParameterName = ""@id"";
            idParameter.Value = id;

            var nameParameter = command.CreateParameter();
            nameParameter.ParameterName = ""@name"";
            nameParameter.Value = name == null ? (object)DBNull.Value : name;

            var descriptionParameter = command.CreateParameter();
            descriptionParameter.ParameterName = ""@description"";
            descriptionParameter.Value = description == null ? (object)DBNull.Value : description;

            var parameters = new DbParameter[]
            {
                idParameter,
                nameParameter,
                descriptionParameter,
            };

            var sqlQuery = @""UPDATE test_entity SET name = @name, description = @description WHERE id = @id"";
            command.CommandText = sqlQuery;
            command.Parameters.AddRange(parameters);
            command.ExecuteNonQuery();
        }
    }
}";
        Assert.AreEqual(expectedOutput, output);
    }

    [TestMethod]
    public void Update_void_Sync_WithOverride()
    {
        string source = @"
#nullable enable
using System.ComponentModel.DataAnnotations.Schema;

namespace Foo
{
    [TableAttribute(""TestEntity"")]
    class TestEntity
    {
        [ColumnAttribute(""Id"")]
        public int Id { get; set; }

        [ColumnAttribute(""Name"")]
        public string Name { get; set; }

        [ColumnAttribute(""Description"")]
        public string Description { get; set; }
    }
    
    [Repository(typeof(TestEntity))]
    partial class C
    {
        private DbConnection connection;

        public partial void Update(int id, string name, string description);
    }
}";
        string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

        Assert.IsNotNull(output);

        var expectedOutput = @"// <auto-generated>
// Code generated by Stored Procedures Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
#pragma warning disable 1591

namespace Foo
{
    using System;
    using System.Collections.Generic;
    using System.Data.Common;
    using System.Linq;

    partial class C
    {
        public partial void Update(int id, string name, string description)
        {
            var connection = this.connection;
            using var command = connection.CreateCommand();

            var idParameter = command.CreateParameter();
            idParameter.ParameterName = ""@id"";
            idParameter.Value = id;

            var nameParameter = command.CreateParameter();
            nameParameter.ParameterName = ""@name"";
            nameParameter.Value = name == null ? (object)DBNull.Value : name;

            var descriptionParameter = command.CreateParameter();
            descriptionParameter.ParameterName = ""@description"";
            descriptionParameter.Value = description == null ? (object)DBNull.Value : description;

            var parameters = new DbParameter[]
            {
                idParameter,
                nameParameter,
                descriptionParameter,
            };

            var sqlQuery = @""UPDATE TestEntity SET Name = @name, Description = @description WHERE Id = @id"";
            command.CommandText = sqlQuery;
            command.Parameters.AddRange(parameters);
            command.ExecuteNonQuery();
        }
    }
}";
        Assert.AreEqual(expectedOutput, output);
    }

    [TestMethod]
    public void Insert_void_Sync()
    {
        string source = @"
#nullable enable
namespace Foo
{
    class TestEntity
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }
    }
    
    [Repository(typeof(TestEntity))]
    partial class C
    {
        private DbConnection connection;

        public partial void Insert(int id, string name, string description);
    }
}";
        string output = this.GetGeneratedOutput(source, NullableContextOptions.Disable);

        Assert.IsNotNull(output);

        var expectedOutput = @"// <auto-generated>
// Code generated by Stored Procedures Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
#nullable enable
#pragma warning disable 1591

namespace Foo
{
    using System;
    using System.Collections.Generic;
    using System.Data.Common;
    using System.Linq;

    partial class C
    {
        public partial void Insert(int id, string name, string description)
        {
            var connection = this.connection;
            using var command = connection.CreateCommand();

            var idParameter = command.CreateParameter();
            idParameter.ParameterName = ""@id"";
            idParameter.Value = id;

            var nameParameter = command.CreateParameter();
            nameParameter.ParameterName = ""@name"";
            nameParameter.Value = name == null ? (object)DBNull.Value : name;

            var descriptionParameter = command.CreateParameter();
            descriptionParameter.ParameterName = ""@description"";
            descriptionParameter.Value = description == null ? (object)DBNull.Value : description;

            var parameters = new DbParameter[]
            {
                idParameter,
                nameParameter,
                descriptionParameter,
            };

            var sqlQuery = @""INSERT INTO test_entity(id, name, description) VALUES (@id, @name, @description)"";
            command.CommandText = sqlQuery;
            command.Parameters.AddRange(parameters);
            command.ExecuteNonQuery();
        }
    }
}";
        Assert.AreEqual(expectedOutput, output);
    }
}
